# -*- coding: utf-8 -*-
"""ex03_0904.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQQHtZIdiAumPu9FRPLjUeCA7dKpwlB5
"""

age = 36
txt = f"My name is John, I am {age}"
print(txt)

txt2 = f"My name is John, I am {age:.2f}"
print(txt2)

txt = "banana"
x = txt.center(20)
print(x)

txt2 = "Hello, welcome to my world."
x2 = txt2.find("welcome")
print(x2)

txt = "THIS IS NOW!"

x = txt.isupper()

print(x)

