# -*- coding: utf-8 -*-
"""pydantic_class.ipynb



Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t67p8jwyVkoY5zsfq1oIQtQCSQG7SZrV
"""

# 사용해야할 또는 사용한 모듈 import        -> import, pip 같은 애들은 적용한 걸 상단에 모아서 적어놓은다
from datetime import datetime
from pydantic import BaseModel, PositiveInt, ValidationError
from typing import Annotated, Literal
from annotated_types import Gt
from pydantic import BaseModel

# class 선언부
class User(BaseModel):
  id: int
  name: str = 'John Doe'
  signup_ts: datetime  | None
  tastes: dict[str, PositiveInt]    # dic 포맷 [문자. 양의정수]-> 출력 [키:값]

# 데이터
external_data = {
    'id' : 123,
    'signup_ts': '2019-06-01 12:22',
    'tastes' : {
        'wine' : 9,
        b'cheese' : 7,     # byte 타입으로 형변
        'cabbage' : '1',   # '1'은 숫자에 ''를 쓴거지만(숫자에는 원래 쓰지않음) 자동형변환으로 숫자로   바꿈
    },
}

# user 오브젝트 생성
user = User(**external_data)     # 유저클래스를 초기화

print(user.id)
print(user.signup_ts)
print(user.tastes)

# 데이터
external_data2 = {'id' : 'not an int', 'tastes' : {}}

try:
  User(**external_data2)    # use = User(**external_data)이지만 파이썬에서는 이름 생략 처리 가능
except ValidationError as e:  # 'e'만 써있는경우 error 줄임말로 쓰임
  print(e.errors())

# class 선언부

class Fruit(BaseModel):
  name: str
  color: Literal['red', 'green']    # 리스트
  weight: Annotated[float, Gt(0)]
  bazam: dict[str, list[tuple[int, bool, float]]]   # tuple : 연속적인 값

print(
    Fruit(               # 클래스 초기화해서 바로 오브젝트로 만듬
        name= 'Apple',
        color= 'red',
        weight= 4.2,
        bazam= {'foobar': [(1, True, 0.1)]}      # tuple : 값으로 들어갈 때 괄호형태로 들어감
    )
)

# class 선언부
class Meeting(BaseModel):
  when: datetime
  where: bytes
  why: str = 'No idea'

# 객체 지정
m = Meeting(when= '2020-01-01T12:00', where= 'home')

print(m.model_dump(exclude_unset=True))      #사용자가 지정하지 않은것은 출력하지 않음 # where 출력시 byte형태로 나옴  b'home'

print(m.model_dump(exclude={'where'}, mode='json'))   # .model_dump() -> 파이덴틱 모들을 일반적인 파이썬 딕트로 변환

print(m.model_dump_json(exclude_defaults=True))