# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXbEq-YaadU1-Vr5LM-5oG1-YcTPpFXP
"""

# !pip install pandas

import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)
print(myvar)

# a column(열) in a table

a = [1,7,2]

s1 = pd.Series(a)
print(s1)

s1[1]

s2 = pd.Series(a, index=["x", "y", "z"])
print(s2)

print(s2["y"])

calories = {"day1": 420, "day2": 380, "day3": 390}

s3 = pd.Series(calories, index = ["day1", "day2"])

print(s3)

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df1 = pd.DataFrame(data)

print(df1)

"""Locate Row
Pandas use the loc attribute to return one or more specified row(s)


"""

#refer to the row -> ` locreturn` 속성을 사용하여 하나 이상의 지정된 행 반
print(df1.loc[0])  # 0번째 행을 반환

#use a list of indexes:
print(df1.loc[[0, 1]])   # 0번째 행과 1번째 행을 반환

df2 = pd.DataFrame(
 {
         "Name": [
             "Braund, Mr. Owen Harris",
             "Allen, Mr. William Henry",
             "Bonnell, Miss Elizabeth",
         ],
         "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
     }
)

print(df2)

print(df2["Age"])

ages = pd.Series([22, 35, 58], name="Age")
print(ages)

df2["Age"].max()

ages.max()

df2.describe()
print(df2.describe())

# 타이타닉 데이터
titanic = pd.read_csv("/content/titanic.csv")
titanic

"""**head/tail은 default 5개**


```
titanic.head()
titanic.tail()
```


"""

titanic.head(8)

titanic.dtypes
print(titanic.dtypes)

titanic.to_excel("titanic.xlsx", sheet_name="passengers", index=False)

titanic = pd.read_excel("titanic.xlsx", sheet_name="passengers")

titanic.head()

titanic.info()

ages = titanic["Age"]

ages.head()

"""**열이 1개 일때는 표시하지 않음** ->
(891,)
"""

type(titanic["Age"])

titanic["Age"].shape

age_sex = titanic[["Age", "Sex"]]
print(age_sex.head())
print(age_sex.tail())

age_sex = titanic[["Age", "Sex"]]

age_sex.head()

type(titanic[["Age", "Sex"]])

titanic[["Age", "Sex"]].shape

above_35 = titanic[titanic["Age"] > 35]

above_35.head()

titanic["Age"] > 35

above_35.shape

class_23 = titanic[titanic["Pclass"].isin([2, 3])]

class_23.head()

class_23 = titanic[(titanic["Pclass"] == 2) | (titanic["Pclass"] == 3)]
class_23.head()

print(class_23.shape)

"""**Pandas의 notna()**는 데이터프레임(DataFrame)이나 시리즈(Series) 내의 **각 값이 결측치(Null, NaN, None)가 아닌지 검사하는 함수**입니다.

동작 방식: 각 요소가 정상적인 데이터이면 True, 결측치(NaN 등)이면 False를 반환합니다.

**주요 용도**: 데이터 전처리 시 **결측치를 제외한 유효한 데이터만 필터링할 때** 주로 사용됩니다.
"""

age_no_na = titanic[titanic["Age"].notna()]
age_no_na.head()

age_no_na.shape

adult_names = titanic.loc[titanic["Age"] > 35, "Name"]

adult_names.head()

titanic.iloc[9:25, 2:5]  # rows 10 till 25 and columns 3 to 5.

"""**rows and/or columns with loc or iloc**"""

titanic.iloc[0:3, 3] = "anonymous"

titanic.iloc[:5, 3]