# -*- coding: utf-8 -*-
"""statement_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vdo8U03-z8Fo8OsXEh5SRUkzzpcG9Mtu
"""

#list와 dict 복합
my_list_dict = [{"name" : "김은영", "age" : 37},  #[0]
                {"name" : "김희영", "age" : 34},  #[1]
                {"name" : "김소영", "age" : 29}   #[2]
                ]

print(my_list_dict[1]["name"])

myfamily = {
    "child1" : "첫째",
    "child2" : "둘째",
    "child3" : "셋째"
    }

print(myfamily)

myfamily = {
    "child1" : {
        "name" : "eunyeong",
        "year" : 1989
        },
    "child2" : {
        "name" : "heeyeong",
        "year" : 1992
        },
    "child3" : {
        "name" : "soyeong",
        "year" : 1997
        }
}

print(myfamily)
print(myfamily["child2"])
print(myfamily["child2"]["name"])

myfamily["child2"]["name"] = "hailey"    # 키의 값을 중간에서 바꿀 수 있다.

print(myfamily["child2"]["name"])
print(myfamily)

ch1 = "eunyeong"
ch2 = "heeyeong"
ch3 = "soyeong"

print(ch1, ch2, ch3)
print(ch1)
print(ch2)
print(ch3)

ch1 = {"name" : "eunyeong", "hobby" : "reading books"}
ch2 = {"name" : "heeyeong", "hobby" : "working out"}
ch3 = {"name" : "soyeong", "hobby" : "painting"}

print(ch1, ch2, ch3)

yourfamily = {}

yourfamily = {
    "ch1" : ch1,
    "ch2" : ch2,
    "ch3" : ch3
}

print(yourfamily)
print(yourfamily["ch1"])
print(yourfamily["ch1"]["name"])

a = 33
b = 200
if b > a:
    print("b is greater than a")

#lambda
print("a") if a > b else print("b")

c = 33
d = 200
if c > d:
    print("c is greater than d")
if c < d:
    print("False")    #print를 따로 적지 않으면 실행하지 않음

#lambda
print("c") if c > d else print("d")

num1 = 50
num2 = 100

if num2 > num1:
  print("100 is greater than 50")
elif num1 == num2:                    # 조건문이 두개 일 경우 elif 사용
  print("num1 is equal to num2")

score = 50

if score >= 90:
  print("Grade: A")
elif score >= 80:       # 조건문이 두개 일 경우 elif 사용
  print("Grade: B")
elif score >= 70:
  print("Grade: C")
elif score >= 60:
  print("Grade: D")
else:                  # 그외 나머지 표현은 else 사용
  print("Grade: F")

#lambda
print("pass") if score > 50 else print("faile")

# 요일값은 월~일 = (1~7) 표기함
day = 9

match day:
  case 1:
    print("Monday")
  case 2:
    print("Tuesday")
  case 3:
    print("Wednesday")
  case 4:
    print("Thursday")
  case 5:
    print("Friday")
  case 6:
    print("Saturday")
  case 7:
    print("Sunday")
  case _:
    print("그 밖의 날")

day =4

# or 의 의미로 '|' 사용
match day:
  case 1 | 2 | 3 | 4 | 5 :
    print("주중입니다")
  case 6 | 7 :
    print("주말입니다")

i = 0

while i < 6:  # 6과 같거나 작은 경우를 뜻함
  i = i + 1   # 값을 반드시 증가시켜야 무한 루프가 돌지 않는다
  print(i)    # (루프를 빠져나갈 방법을 먼저 적기)

i = 0

# while이 로직을 수행하다가 빠져나가는 방법 if문
while i < 6 :
  if i == 3 :   # i가 3이 되면 루프를 종료
    break
  i = i + 1
  print(i)

i = 0

#continue를 만나면, while loop 끝난다
while i < 6 :
  i +=1         # i = i + 1 같은 의미
  if i == 3 :
    continue
  print(i)

i = 1
while i < 6:
  print(i)
  i += 1
else:
  print("i is no longer less than 6")

# x"바나나"가 되면 루프를 종료

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
  if x == "banana":
    break

# "banana"가 되면 루프를 종료하되 x, 이번에는 출력 전에 중단

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    break
  print(x)

# 2차원은 [행x, 열y]이라고 생각하자
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)